### ISSUE TITLE
Malloc abuse

### ISSUE THREAD

**Issue by batbucket** [JonathanHunter/Nullptr#14]
If a player shoots Malloc blocks beneath them and spams jump, they can pretty much get past any level akin to the Cape in Super Mario World.

My world record, no-hit speedrun of the Kernel:
https://streamable.com/6aew

**Comment by JonathanHunter** [comment]
THIS IS AMAZING ( •o•).  I am going to consider this a feature/speedrun strat and leave it in, but we will need to add a ceiling to all the levels now.

**Comment by NealKaviratna** [comment]
Kreygasm

**Comment by JonathanHunter** [comment]
Ceilings added on @bca7983
